# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 14:58
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Graph list',
                'verbose_name': 'Graph',
            },
        ),
        migrations.CreateModel(
            name='GraphData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='JSON graph data')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_graph.Graph')),
            ],
        ),
        migrations.CreateModel(
            name='GraphModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
            ],
            options={
                'verbose_name_plural': 'Graph models',
                'verbose_name': 'Graph model',
            },
        ),
        migrations.CreateModel(
            name='GraphModelDrawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('json', django.contrib.postgres.fields.jsonb.JSONField(null=True, verbose_name='json')),
            ],
            options={
                'verbose_name_plural': 'Graph model drawings',
                'verbose_name': 'Graph model drawing',
            },
        ),
        migrations.CreateModel(
            name='GraphNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_graph.Graph')),
                ('graph_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_graph.GraphData')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_graph.GraphModel')),
            ],
        ),
        migrations.CreateModel(
            name='GraphNodeEdge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_graph.GraphNode')),
            ],
        ),
        migrations.CreateModel(
            name='GraphRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('from_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('to_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('graph', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_graph.Graph')),
            ],
            options={
                'verbose_name_plural': 'Graph relations',
                'verbose_name': 'Graph relation',
            },
        ),
        migrations.AddField(
            model_name='graphnodeedge',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_graph.GraphRelation'),
        ),
        migrations.AddField(
            model_name='graphnodeedge',
            name='to_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_graph.GraphNode'),
        ),
        migrations.AddField(
            model_name='graphmodel',
            name='drawing',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='data_graph.GraphModelDrawing'),
        ),
        migrations.AddField(
            model_name='graphmodel',
            name='graph',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data_graph.Graph'),
        ),
    ]
