# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='graphobject',
            options={'verbose_name': 'Graph Object', 'verbose_name_plural': 'Graph Objects'},
        ),
        migrations.AlterModelOptions(
            name='graphobjectdrawing',
            options={'verbose_name': 'Graph Object Drawing', 'verbose_name_plural': 'Graph Object Drawings'},
        ),
        migrations.AddField(
            model_name='graphobjectdrawing',
            name='name',
            field=models.CharField(default='n1', max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
