# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_graph', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='graphnodeedge',
            unique_together=set([('from_node', 'to_node')]),
        ),
    ]
