# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_graph', '0002_auto_20171213_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graphnodeedge',
            name='from_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_node', to='data_graph.GraphNode'),
        ),
        migrations.AlterField(
            model_name='graphnodeedge',
            name='to_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_node', to='data_graph.GraphNode'),
        ),
    ]
