# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-26 11:03
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data_graph', '0002_modeltemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('from_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('to_fields', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None)),
                ('comparators', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('equal', 'equal'), ('similar', 'similar'), ('translit_similar', 'translit_similar')], default='equal', max_length=50), help_text="choose from 'equal, similar, translit_similar', write without whitespaces", size=None)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Relation template',
                'verbose_name_plural': 'Relation templates',
            },
        ),
    ]
