# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 07:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_graph', '0003_auto_20171213_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='graph',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
