# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 20:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_graph', '0004_graph_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='graph',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
